(load "core")
(use 'parse-interp.core)
(-main '(4))
(-main '(+ 1 2))
(-main '(+ (- 4 4) 5))
(-main '(with ((x (+ 5 5))) (with (y (- x 3)) (+ y y))))
(-main '(with ((x (+ 5 5)) (y (+ 3 3))) (+ x y)))
(-main '(with ((x (+ 5 5)) (x (+ 3 3))) (+ x x)))
